### definitions ###

include $(DOGPACK)/lib/Makefile.defs # inherit interface
include $(DOGPACK)/apps/plasma/lib/Makefile.defs

### targets ###

lib: $(ALL_OBJECTS)

include $(DOGPACK)/lib/Makefile.targets

### DO NOT remove this line - make depends on it ###
