
### definitions ###

# default/library definitions
COMPILE_WITH_UNST = 1
include $(DOGPACK)/lib/2d/Makefile.defs

# overridden library objects
#
SetBndValues_Unst = SetBndValues_Unst
#Output_Unst       = Output_Unst

ALL_OBJECTS = $(COMMON_OBJECTS)
ALL_SOURCES = $(COMMON_SOURCES)

### targets ###

include $(DOGPACK)/lib/2d/Makefile.targets

### DO NOT remove this line - make depends on it ###
