### definitions ###

# default/library definitions
include $(DOGPACK)/lib/1d/Makefile.defs

# overridden library objects
#
InitApp  =  InitApp
AfterStep = AfterStep
BeforeStep = BeforeStep

# place to add object modules
#
ALL_OBJECTS = $(COMMON_OBJECTS) \
QuadMomentParams.o \


ALL_SOURCES = $(COMMON_SOURCES) \
QuadMomentParams.cpp \


### targets ###

include $(DOGPACK)/lib/1d/Makefile.targets

### DO NOT remove this line - make depends on it ###
