# apps/plasma/lib/sys/Makefile

# This directory inherits from dogpack/lib/sys
# (and not from intrinsic dogpack libraries)
include $(DOGPACK)/lib/sys/Makefile.defs
include $(DOGPACK)/apps/plasma/lib/sys/Makefile.defs

### targets ###

lib: $(ALL_OBJECTS) $(ALL_SOURCES)

include $(DOGPACK)/lib/sys/Makefile.targets

### DO NOT remove this line - make depends on it ###
