### definitions ###

# default/library definitions
include $(DOGPACK)/lib/1d/Makefile.defs

# overridden library objects
InitApp = InitApp

# place to add object modules
#
ALL_OBJECTS = $(COMMON_OBJECTS) \
TwoFluidParams.o

ALL_SOURCES = $(COMMON_SOURCES) \
TwoFluidParams.cpp

### targets ###

include $(DOGPACK)/lib/1d/Makefile.targets

### DO NOT remove this line - make depends on it ###
