### definitions ###

# default/library definitions
include $(DOGPACK)/lib/1d/Makefile.defs

# overridden library objects
#
AfterStep            = AfterStep
LstarExtra           = LstarExtra

# place to add object modules
#
#ALL_OBJECTS = $(COMMON_OBJECTS) ...

### targets ###

include $(DOGPACK)/lib/1d/Makefile.targets

### DO NOT remove this line - make depends on it ###
