# To make the executable, type:  make

### definitions ###

# get default/library definitions
include $(DOGPACK)/lib/2d/Makefile.defs

# overridden library definitions
#
LstarExtra = LstarExtra

ALL_OBJECTS = \
$(COMMON_OBJECTS) \
AppSolver.o \

ALL_SOURCES = \
$(COMMON_SOURCES) \
AppSolver.cpp \

### targets ###

include $(DOGPACK)/lib/2d/Makefile.targets

### DO NOT remove this line - make depends on it ###
