# This directory contains two-fluid plasma solvers.
# (gas dynamics for each species coupled to Maxwell's equations)
#
# g10   : 10-moment gas dynamics for each species
# g05   :  5-moment gas dynamics for each species
# p10   : 10-moment symmetric pair plasma
# p05   :  5-moment symmetric pair plasma
# i10e5 : 10-moment ion fluid and 5-moment electron fluid
